spring.application.name=app

# JWT
app.jwt.secret=${JWT_SECRET:5367566B59703373736739792F423F4528482B4D6251655468576D5A71347437}
app.jwt.expiration-ms=86400000

# MYSQL - pakai env var untuk production (Railway), fallback ke lokal
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/financebuddy?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Farakha19.}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Gmail SMTP (OTP Email)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true