spring.application.name=app

# JWT
app.jwt.secret=5367566B59703373736739792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/financebuddy?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Farakha19.

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ─── Gmail SMTP (OTP Email) ───────────────────────────────────────────────────
# Ganti dengan Gmail kamu + App Password (bukan password biasa!)
# Cara buat App Password: myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=faridhakim1234a@gmail.com
spring.mail.password=jese bfqh jyvb jnzh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true